language: node_js
node_js:
- '6'
before_install:
- npm i npm-cli-login -g
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "e1IEtZ4vdMbe6U3AgxpdvChEvv1UII6vo+ne7ESpJtznnFgAh2DmTN8GPa+lsINJu3cs8gP3Fq1y376gHUXe4XE7ENuKMtM7Mon3Yu8kqTpKDk6qIlTDn6cxNZoxGVMPhHgOzIdW01d2738Cj4j2YZNI9erGsVytjHAgxxwpCOkMLpYMPZ5k9daY0b7HnOvNQJcR+vecF8TJ9qyojPqXEYUjkJCIfAG8zeENRv+XsfwyDMAw9UmIX/BnaHIL5FF8A6AIwQ3io2wMwTqIXzKGJ0Vc2fscHIvXc7hGx0/K3Y05HMnPtEWQpdUeMdLj15qDPfKp3LVCpJ5IvPDQmF38wahzavbOEoyHXzRTC95osQVJImdZTwhktoTOlk5CSqGv5t+rYtUmeX5FywaPpzL1o2O2tQtL8qUt8ogNSGlDl/t7Gu3LB+Lk7ji6W/Va28iGebgZIhymK7BGhXA1wn/wmKJTyObfqenFYuWD8y44vw5IK7EPbDmcyM4KtQu3IIjupfH59UIytozeL5eLttRBxUbUbancCL0uNoeEh1gVykn5pXsUnZnHqBhAloip9Hw9s+PKc6SAGxU31HoLDRYebclJR9j+IiYh7URADPKeYrPn/+ekm0EKTJFB+WUm13uUzXsMFUJPHBYMItGmnIIiv5QtpFWgocwpH7zv9ynrMKU="
